# Generated by Django 4.2.10 on 2024-03-12 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Publisher's name", max_length=300)),
                ('website', models.URLField(help_text="Publisher's website")),
                ('email', models.EmailField(help_text="Publisher's email address", max_length=254)),
            ],
        ),
    ]
