# Generated by Django 4.2.10 on 2024-03-21 15:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Reviews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Book title', max_length=200)),
                ('publication_date', models.DateField(verbose_name='Book published date')),
                ('isbn', models.CharField(max_length=20, verbose_name='ISBN number of the book')),
            ],
        ),
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text="contributor's first name", max_length=200)),
                ('last_name', models.CharField(help_text="contributor's last name", max_length=200)),
                ('email', models.EmailField(help_text="Contributor's email address", max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Users Review')),
                ('rating', models.IntegerField(help_text='Rating of reviewer')),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='Date and time of review')),
                ('date_edited', models.DateTimeField(help_text='Date and time review was updated', null=True)),
                ('book', models.ForeignKey(help_text='Book review was made on', on_delete=django.db.models.deletion.CASCADE, to='Reviews.book')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BookContributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('AUTHOR', 'Author'), ('CO-AUTHOR', 'Co-Author'), ('EDITOR', 'Editor')], max_length=20, verbose_name='Role of this contributor')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reviews.book')),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reviews.contributor')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='contributors',
            field=models.ManyToManyField(through='Reviews.BookContributor', to='Reviews.contributor'),
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reviews.publisher'),
        ),
    ]
